/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProposalSentRouteImport } from './routes/proposal-sent'
import { Route as ApiPublicCatalogSyncRouteImport } from './routes/api/public/catalog-sync'
import { Route as ApiPublicWebhooksStripeRouteImport } from './routes/api/public/webhooks/stripe'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProposalSentRoute = ProposalSentRouteImport.update({
  id: '/proposal-sent',
  path: '/proposal-sent',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCatalogSyncRoute = ApiPublicCatalogSyncRouteImport.update({
  id: '/api/public/catalog-sync',
  path: '/api/public/catalog-sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhooksStripeRoute = ApiPublicWebhooksStripeRouteImport.update({
  id: '/api/public/webhooks/stripe',
  path: '/api/public/webhooks/stripe',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/proposal-sent': typeof ProposalSentRoute
  '/api/public/catalog-sync': typeof ApiPublicCatalogSyncRoute
  '/api/public/webhooks/stripe': typeof ApiPublicWebhooksStripeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/proposal-sent': typeof ProposalSentRoute
  '/api/public/catalog-sync': typeof ApiPublicCatalogSyncRoute
  '/api/public/webhooks/stripe': typeof ApiPublicWebhooksStripeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/proposal-sent': typeof ProposalSentRoute
  '/api/public/catalog-sync': typeof ApiPublicCatalogSyncRoute
  '/api/public/webhooks/stripe': typeof ApiPublicWebhooksStripeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/proposal-sent'
    | '/api/public/catalog-sync'
    | '/api/public/webhooks/stripe'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/proposal-sent'
    | '/api/public/catalog-sync'
    | '/api/public/webhooks/stripe'
  id:
    | '__root__'
    | '/'
    | '/proposal-sent'
    | '/api/public/catalog-sync'
    | '/api/public/webhooks/stripe'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProposalSentRoute: typeof ProposalSentRoute
  ApiPublicCatalogSyncRoute: typeof ApiPublicCatalogSyncRoute
  ApiPublicWebhooksStripeRoute: typeof ApiPublicWebhooksStripeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proposal-sent': {
      id: '/proposal-sent'
      path: '/proposal-sent'
      fullPath: '/proposal-sent'
      preLoaderRoute: typeof ProposalSentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/catalog-sync': {
      id: '/api/public/catalog-sync'
      path: '/api/public/catalog-sync'
      fullPath: '/api/public/catalog-sync'
      preLoaderRoute: typeof ApiPublicCatalogSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/stripe': {
      id: '/api/public/webhooks/stripe'
      path: '/api/public/webhooks/stripe'
      fullPath: '/api/public/webhooks/stripe'
      preLoaderRoute: typeof ApiPublicWebhooksStripeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProposalSentRoute: ProposalSentRoute,
  ApiPublicCatalogSyncRoute: ApiPublicCatalogSyncRoute,
  ApiPublicWebhooksStripeRoute: ApiPublicWebhooksStripeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
